### PR TITLE
Final Milestone: Final Version of thenextweb.com clone

### PR DESCRIPTION
**Pull request by AhmedTohamy01**
**This is a final version of the clone of thenextweb.com website, this version includes:**

- header section like the original website.
- main section including 3 main photos like the original website.
- latest news web part.
- latest funding web part.
- categories web part.
- latest deals web part.
- footer.

**The website is fully responsive .**

### CODE REVIEW

**Comment by mikenath223** [comment]
### Pull request currently under review by Michgolden Ukeje (TSE).
Kindly exercise patience 👋

**Comment by AhmedTohamy01** [comment]
Dear Mike, Thank you for your review, here is our reply for your comments:

**- For point 1 :**
It's NOT a requirement in the project to use float specifically in the navbar , we already used float with another elements, please read the **core project requirements**. 

**- For point 2 :**
Again, this is NOT from the core requirements in the project , the project is to measure our ability to make a responsive design. there are a LOT of details in this project and as per Odin Project instructions **"Don’t get lost in the details – it’s okay if it isn’t exact."**

**- For point 3:**
Again, this is NOT from the core requirements in the project , the project is to measure our ability to make a responsive design. Number of cards is NOT Important. again, as per Odin Project instructions **"Don’t get lost in the details – it’s okay if it isn’t exact."**

**- For point 4:**
We already fixed this scroll, Thank you for notifying us.

Now i think it's time to approve.

**Comment by AhmedTohamy01** [comment]
Dear Mike, Thank you for your review, here is our reply for your comments:

**- For point 1 :**
It's NOT a requirement in the project to use float specifically in the navbar , we already used float with another elements, please read the **core project requirements**. 

**- For point 2 :**
Again, this is NOT from the core requirements in the project , the project is to measure our ability to make a responsive design. there are a LOT of details in this project and as per Odin Project instructions **"Don’t get lost in the details – it’s okay if it isn’t exact."**

**- For point 3:**
Again, this is NOT from the core requirements in the project , the project is to measure our ability to make a responsive design. Number of cards is NOT Important. again, as per Odin Project instructions **"Don’t get lost in the details – it’s okay if it isn’t exact."**

**- For point 4:**
We already fixed this scroll, Thank you for notifying us.

Now i think it's time to approve.

**Comment by uryelah** [comment]
Hey guys, I'm Sarah, your last reviewer for this PR 👩‍🚀  

Great job fixing the horizontal scroll issue, about the navbar I think my colleague meant to say that the navbar should be fixed, get ready for the next project, the bootstrap one will require a perfect clone 😃 

------
## Your project is approved!  
### 
**You may close this Pull Request and merge the changes**

----

**Keep being an awesome dev and good luck with your next project!**

Cheers and Happy coding!👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

**Comment by AhmedTohamy01** [comment]
Thank you so much Sarah @uryelah .

Much Appreciated :)

**Pull request merged**
